# Generated by Django 4.2.3 on 2023-10-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fota_Ecu",
            fields=[
                ("ecu_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Fota_Firmware",
            fields=[
                ("firmware_id", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("firmware", models.FileField(upload_to="firmwares/")),
                ("is_active", models.BooleanField(default=False)),
                ("firmware_cmac", models.CharField(max_length=1024)),
                ("firmware_size", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="mqtt",
            fields=[
                ("mqtt_id", models.AutoField(primary_key=True, serialize=False)),
                ("broker", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField()),
                ("client_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("ka_topic", models.CharField(max_length=255)),
                ("pub_topic", models.CharField(max_length=255)),
                ("sub_topic", models.CharField(max_length=255)),
                ("out_msg", models.CharField(max_length=1024)),
                ("in_msg", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Fota_Vehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "ecu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.fota_ecu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fota_Fota",
            fields=[
                ("fota_id", models.AutoField(primary_key=True, serialize=False)),
                ("availability_flag", models.BooleanField(default=False)),
                ("update_ready_flag", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("minutes_taken", models.PositiveIntegerField(default=0)),
                (
                    "ecu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.fota_ecu",
                    ),
                ),
                (
                    "firmware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.fota_firmware",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.fota_vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fota_ecu",
            name="firmware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.fota_firmware"
            ),
        ),
    ]
